apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-app
  template:
    metadata:
      labels:
        app: gateway-app
    spec:
      imagePullSecrets:
        - name: my-new-secret
      containers:
      - name: gateway
        image: sarfarazengglb/webpush-microservices-image-repo:gateway-service-v0.0.1
        ports:
        - containerPort: 8087
